export enum AuthErrorCode {
  // Registration errors
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',

  // Login errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  NO_HOTEL_ASSOCIATED = 'NO_HOTEL_ASSOCIATED',

  // Token errors
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',

  // Email confirmation errors
  INVALID_CONFIRMATION_TOKEN = 'INVALID_CONFIRMATION_TOKEN',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',

  // Password reset errors
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  INVALID_TOKEN_CONTEXT = 'INVALID_TOKEN_CONTEXT',
  INVALID_TOKEN_USER = 'INVALID_TOKEN_USER',
}

export enum AuthSuccessCode {
  // Registration success
  REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS',

  // Navigation success
  NAVIGATION_STEP_UPDATED = 'NAVIGATION_STEP_UPDATED',

  // Email confirmation success
  EMAIL_CONFIRMED = 'EMAIL_CONFIRMED',
  CONFIRMATION_EMAIL_SENT = 'CONFIRMATION_EMAIL_SENT',

  // Password reset success
  RESET_EMAIL_SENT = 'RESET_EMAIL_SENT',
  PASSWORD_UPDATED = 'PASSWORD_UPDATED',
}
